version: '2'

services:
  mysql:
    container_name: mysql
    build:
      context: .
      dockerfile: Dockerfile-mysql
    restart: always
    ports:
      - "3306:3306"

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile-app
    depends_on:
      - mysql
    ports:
      - "8001:8001"
    restart: always
